# Generated by Django 5.2.4 on 2025-07-18 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quran', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('SIMILAR', 'Similar verses'), ('SIM_RUB', 'Similar + Quarter'), ('MIXED', 'Mixed'), ('MAP', 'Full mapping')], max_length=10)),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=1)),
                ('num_questions', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_page', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('selected_half', models.CharField(blank=True, choices=[('TOP', 'Top half'), ('BOTTOM', 'Bottom half')], max_length=6)),
                ('is_correct', models.BooleanField(default=False)),
                ('ayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.ayah')),
                ('selected_quarter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quran.quarter')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.testsession')),
            ],
        ),
    ]
