# Generated by Django 5.2.4 on 2025-07-17 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Hizb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('juz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hizbs', to='quran.juz')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('hizb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='quran.hizb')),
            ],
            options={
                'ordering': ['hizb__number', 'number'],
                'unique_together': {('hizb', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('page_number', models.PositiveSmallIntegerField()),
                ('page_half', models.CharField(choices=[('TOP', 'Top half'), ('BOTTOM', 'Bottom half')], max_length=6)),
                ('hizb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayahs', to='quran.hizb')),
                ('juz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayahs', to='quran.juz')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayahs', to='quran.quarter')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayahs', to='quran.surah')),
            ],
            options={
                'ordering': ['surah__number', 'number'],
                'unique_together': {('surah', 'number')},
            },
        ),
    ]
